language : java
install :
    - cd pc
    - echo "SIMULE_SERIE = true" > config.ini
    - echo "GRAPHIC_DIFFERENTIAL = false" >> config.ini
    - echo "GRAPHIC_EXTERNAL = false" >> config.ini
    - cat config.ini
script :
    - ant
    - timeout 180 ant tests
jdk :
    - oraclejdk8
notifications:
    slack: intech-sudparis:Z3xKQEmZT2a9BFBqouokQ6J7
    on_success: change
    on_failure: always
branches:
    only : master
